name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build (Windows x64, MSVC)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd src
          nmake /f Makefile.msvc BUILDMODE=static

      - name: Package artifacts
        shell: bash
        run: |
          mkdir -p artifact
          cp src/luajit.exe artifact/
          cp src/*.dll artifact/ || true
          cp src/*.lib artifact/ || true
          zip -r LuaJIT-windows-msvc-x64.zip artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuaJIT-windows-msvc-x64
          path: LuaJIT-windows-msvc-x64.zip

  build-linux:
    name: Build (Linux x64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install them build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build!!!
        run: |
          cd src
          make CC=gcc BUILDMODE=static

      - name: Package artifacts
        run: |
          mkdir -p artifact
          cp src/luajit artifact/
          cp src/*.so artifact/ || true
          tar -czf LuaJIT-linux-x64.tar.gz artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuaJIT-linux-x64
          path: LuaJIT-linux-x64.tar.gz
